name: azaleasays
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: azalea says
timezone: America/New_York
subscribe: http://azalea.github.io/feed.xml
