name: azaleasays
markdown: kramdown
exclude: [ README.md, newpost.rb, CNAME ]
permalink: /:year/:month/:day/:title
title: azalea says
timezone: America/New_York
subscribe: http://azaleasays.com/atom.xml
githubEditBaseURL: https://github.com/azalea/azalea.github.io/edit/master/
disqusShortname: azaleasays
url: http://azaleasays.com
